version: '3.9'
services:
    service_backend:
        build: ./backend
        ports: 
            - 5000:5000

    service_redis:
        image: "redis"
        ports: 
            - 6379:6379

    service_frontend:
        build: ./frontend
        ports:
            - 8000:80
